// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYTt26m8ovkNqCEl9gvUFGHImo4I8GVik',
    appId: '1:219394341327:web:34c06322ae8a124f60baba',
    messagingSenderId: '219394341327',
    projectId: 'fir-push-eca50',
    authDomain: 'fir-push-eca50.firebaseapp.com',
    storageBucket: 'fir-push-eca50.appspot.com',
    measurementId: 'G-315Q062CB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsV2N1j6fl23bcywnGTM6zL4xn-RRWTAw',
    appId: '1:219394341327:android:f5def3e930d750d360baba',
    messagingSenderId: '219394341327',
    projectId: 'fir-push-eca50',
    storageBucket: 'fir-push-eca50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7UoN32ixfJudK4CnUyzvj1CNo0zUCh08',
    appId: '1:219394341327:ios:06761489e59176f460baba',
    messagingSenderId: '219394341327',
    projectId: 'fir-push-eca50',
    storageBucket: 'fir-push-eca50.appspot.com',
    androidClientId: '219394341327-o3ad7gr6m02hfvll988bfbneunjuhj1n.apps.googleusercontent.com',
    iosClientId: '219394341327-jfum0cncnuspopnnauv12kcgjeko0ms3.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushnotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7UoN32ixfJudK4CnUyzvj1CNo0zUCh08',
    appId: '1:219394341327:ios:d576518b310fcad060baba',
    messagingSenderId: '219394341327',
    projectId: 'fir-push-eca50',
    storageBucket: 'fir-push-eca50.appspot.com',
    androidClientId: '219394341327-o3ad7gr6m02hfvll988bfbneunjuhj1n.apps.googleusercontent.com',
    iosClientId: '219394341327-9jtbqvglv9kghhv95v83046rjniu1h8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushnotification.RunnerTests',
  );
}
